spring:
  application:
   name: Basket
  cloud:
   azure:
    servicebus:
     namespace: saproneservicebus
     entity-name: basket-queue
     entity-type: queue
     connection-string: ${SERVICE_BUS_CONNECTION_STRING}